apiVersion: v1
kind: Pod
metadata:
  namespace: kiii-real-time-chat
  name: real-time-chat-pod-api
  labels:
    app.kubernetes.io/name: real-time-chat-api-container
spec:
  containers:
    - name: real-time-chat-api-container
      image: stefanijaduracoska/kiii_project_api
      ports:
        - containerPort: 5000
      envFrom:
        - secretRef:
            name: runtime-secrets-api
