apiVersion: v1
kind: Secret
metadata:
  namespace: kiii-real-time-chat
  name: runtime-secrets-web
type: Opaque
stringData:
  PORT: "3000"
  HOST: "0.0.0.0"
  BRANCH_NAME: "main"
  BUILD_NUMBER: "1"
  NEXTAUTH_SECRET: "secret"
  BACKEND_URL: "http://api-service:5000"
  HUB_ID: "Iv1.8c1bb31195ebb8ff"
  HUB_SECRET: "57079a7361ccf7c317fcea405923b72558c6899e"
  WEBSOCKET_PORT: "3300"
  NEXT_PUBLIC_SOCKET_URL: "socket.real-time-chat.com"
  NEXTAUTH_URL: "http://web.real-time-chat.com"
