on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: "./api.Dockerfile"
          tags: stefanijaduracoska/kiii_project:latest
          build-args: |
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            PORT=${{ secrets.PORT }}
            HOST=${{ secrets.HOST }}
            BRANCH_NAME=${{ secrets.BRANCH_NAME }}
            DB_INITIAL_PORT=${{ secrets.DB_INITIAL_PORT }}
            BUILD_NUMBER=${{ secrets.BUILD_NUMBER }}
            BACKEND_URL=${{ secrets.BACKEND_URL }}
            HUB_ID=${{ secrets.HUB_ID }}
            HUB_SECRET=${{ secrets.HUB_SECRET }}
            WEBSOCKET_PORT=${{ secrets.WEBSOCKET_PORT }}
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: "./web.Dockerfile"
          tags: stefanijaduracoska/kiii_project:latest
          build-args: |
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            BACKEND_URL=${{ secrets.BACKEND_URL }}
            HUB_ID=${{ secrets.HUB_ID }}
            HUB_SECRET=${{ secrets.HUB_SECRET }}
            NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_PUBLIC_SOCKET_URL }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            BUILD_NUMBER=${{ secrets.BUILD_NUMBER }}
            BRANCH_NAME=${{ secrets.BRANCH_NAME }}
